# Generated by Django 5.1.1 on 2024-10-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('km_driven', models.PositiveIntegerField()),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('fuel', models.CharField(max_length=20)),
                ('seller_type', models.CharField(max_length=20)),
                ('transmission', models.CharField(max_length=20)),
                ('owner', models.CharField(max_length=20)),
                ('mileage', models.FloatField()),
                ('engine', models.FloatField()),
                ('max_power', models.FloatField()),
                ('seats', models.PositiveIntegerField()),
                ('region', models.CharField(max_length=20)),
            ],
        ),
    ]
