# Generated by Django 5.1.1 on 2024-10-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsale',
            name='pred_price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
